[build]
edge_functions = "edge"
[[headers]]
for = "*"
[headers.values]
Access-Control-Allow-Origin = "https://www.geoscout.uk"
Content-Security-Policy = "default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.googleapis.com https://*.gstatic.com *.google.com https://*.ggpht.com *.googleusercontent.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' https://*.googleapis.com https://*.gstatic.com *.google.com  *.googleusercontent.com data: https:; connect-src 'self' https://*.googleapis.com *.google.com https://*.gstatic.com https://api.what3words.com data: blob:; font-src 'self' data: https://fonts.gstatic.com; manifest-src 'self'; frame-src *.google.com; worker-src 'self' blob:;"
Expect-CT = "max-age=86400, enforce"
Permissions-Policy = "accelerometer=(), autoplay=(), camera=(self), cross-origin-isolated=(), encrypted-media=(self), fullscreen=(*), geolocation=(self), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(self), xr-spatial-tracking=()"
Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "0"
# Testing for new security headers (Cross-Origin)
# COEP
Cross-Origin-Embedder-Policy-Report-Only = "require-corp"
# COOP
Cross-Origin-Opener-Policy-Report-Only = "same-origin"
# CORP
Cross-Origin-Resource-Policy-Report-Only = "same-origin"
[functions]
directory = "functions/"
included_files = ["functions/cert.pem"]
node_bundler = "esbuild"
[[edge_functions]]
function = "social-image"
path = "/share*"
[[redirects]]
force = true
from = "https://geoscout.netlify.app/*"
status = 301
to = "https://www.geoscout.uk/:splat"
[[redirects]]
force = true
from = "https://geocaching.withamscouts.org.uk/*"
status = 302
to = "https://www.geoscout.uk/:splat"
[[redirects]]
force = true
from = "/api/*"
status = 200
to = "/.netlify/functions/:splat"
[[redirects]]
force = true
from = "/profilePic/*"
status = 200
to = "/.netlify/builders/get-avatar"
[[redirects]]
from = "/*"
status = 200
to = "/index.html"
[dev]
autoLaunch = false
